### ISSUE TITLE
Feature Request: Strum/Arpeggiate Function

### ISSUE THREAD

**Issue by m-mahan** [adamjmurray/ableton-midi-sculptor#1]
Hey Adam, thank you so much for this fantastic device!

I was wondering if it might be possible to implement a strum/arpeggiate feature under one of the tabs as a drop down menu option?

I was thinking it might be possible to implement in the following way, but my max midi note data knowledge is pretty limited:

Strum/Arpeggiate:
- Take the lowest pitch value, and offset all following notes, relative to the preceding note, with respect to the value defined in "Range". It would also be great if the notes could maintain the same end value as the lowest note. 

A descending strum would function similarly, but starting with the highest note and offsetting each following note in a downward manner. 

You could then apply this to a chord in which all notes are of equal length, and depending on the settings end up with a nice tight strum, or something more extreme. 

The FL Studio strum tool functions similar to this and it has some great features. If you're not familiar with it you can check the documentation here for a more detailed look at how it works: [https://www.image-line.com/support/flstudio_online_manual/html/pianoroll_strum.htm](url)

Last but not least, this is one of the best M4L devices I've come across and I would be happy to donate towards it's continued development if you wanted to set up a paypal button or something.

Thanks again for the awesome device!
-Matt

**Comment by adamjmurray** [comment]
Thanks for the feedback and feature request @m-mahan! I have a bunch of feature ideas for upcoming versions of the device, but I hadn't considered a strum tool. I think that fits in nicely with the spirit of this device and doesn't seem too difficult to build, so I'll definitely consider adding it. If/when that happens I'll close this issue and let you know a new version is available.

I really appreciate your offer to donate. I added a Paypal donate button toward the bottom of the [project's home page/README](https://github.com/adamjmurray/ableton-midi-sculptor#support-this-project).

**Comment by m-mahan** [comment]
Awesome, thanks @adamjmurray !

I meant to respond a few weeks ago, but I sent in a donation and I can't wait to see what you come up with in the coming versions!

**Comment by adamjmurray** [comment]
Thank you so much @m-mahan !

I've been too busy to work on this the last couple months, but I definitely still want to continue developing this device.

**Comment by adamjmurray** [comment]
@m-mahan I finally have a strum feature ready. If you want to test out a pre-release version you can get it here: https://github.com/adamjmurray/ableton-midi-sculptor/raw/1.1/releases/beta/Sculptor-1.09.amxd

There is a new option "strum" in the slide tab's drop down menu. The behavior is hopefully intuitive. This gif demonstrates the features. Note the lock button next to the end time slider. Let me know what you think!

![strum](https://user-images.githubusercontent.com/12264/99359241-a0d32e80-2863-11eb-81c0-7978c7915d2f.gif)

**Comment by BDrej** [comment]
@adamjmurray oh =0 that looks awesome 
i will try it immediately out when im @ home.

**Comment by m-mahan** [comment]
@adamjmurray This looks amazing, thanks so much!!

Stoked to try it out, I'll let you know if I run into any issues!

**Comment by adamjmurray** [comment]
@BDrej @m-mahan Good news (mostly): I've been beta testing Live 11, and Max devices have access to the new note features: probability and velocity range. See https://www.ableton.com/en/live/#chance-tools. I will be updating this device to support it so we can randomize our randomness 😂 

(Side note: Live 11 is really awesome IMHO. I think all the new features are fantastic!)

The only issue is it is not backward compatible. I am going to focus on having an official release of this device for Live 10 with the new strum feature by the end of the year. After that I am going to focus on new Live 11 features. **That means future releases will require Live 11.**

In any case, if you find any bugs, I'll get those fixed in the coming weeks (I actually have spare time during the holidays), and hopefully this device will continue to serve you well with the current features even if you stay on Live 10 for a while.

**Comment by BDrej** [comment]
I love the update 
till now didnt find any issues (not sooo many hours into production the last days) but thats a really cool way to fire up strum onto midi notes. 
Oh yeah i think randomising the randomness in 11 would be cool 💯

**Comment by adamjmurray** [comment]
Cleaning up old issues. I don't think there's anything else to do here.
