### ISSUE TITLE
notes vanishing

### ISSUE THREAD

**Issue by Hifilo** [adamjmurray/ableton-midi-sculptor#6]
Hi, Your device is very good, but i can't seem to figure out which settings to use to prevent notes vanishing on contact. Is there a specific way to use it so notes do not vanish on touch?

Thank you

**Comment by adamjmurray** [comment]
Hi, unfortunately no, not right now. The Ableton Live API usually deletes notes when they overlap. Maybe I can make the device smarter about this in a future version by "squishing" notes so they don't overlap, but it is difficult to do this well. 

I am guessing you are randomizing the start times or durations of a bunch of notes and this is causing some frustration? One suggestion is to select all the notes and shrink all their lengths so there is space in between them, and randomize in small amounts so they don't overlap as much. 

Another tip: if you loop the clip you are editing, and keep dragging with the mouse/trackpad while randomizing, it will restore notes that have disappeared if space opens back up for them. The notes don't get completed deleted until you let go of the mouse/trackpad. If you are ok with some notes being deleted, dragging around on the randomize pad is a good way to hear different variations without losing too many notes. If you move the pad exactly to the center, all the notes should come back. In general, the closer you stay to the center of the randomize pad, the less the notes will move and disappear.

Hopefully that made sense, and I hope that helps a little bit!

**Comment by adamjmurray** [comment]
@Hifilo, thanks for bringing this up. I took another look with fresh eyes and found a good way to "squish" the notes so they generally won't get deleted. If the notes shrink very small (smaller than a 1/1024th note), they will still get deleted, but this shouldn't be an issue in practice. 

If you try again with the new version [v2.0 beta 2](https://github.com/adamjmurray/ableton-midi-sculptor/blob/master/releases/2.0-beta-2/Sculptor.amxd?raw=true), it should work a lot better now!

**Comment by higaru2** [comment]
thanks Adam!!!
also waiting for the new Live to get out of beta.

**Comment by Hifilo** [comment]
> @Hifilo, thanks for bringing this up. I took another look with fresh eyes and found a good way to "squish" the notes so they generally won't get deleted. If the notes shrink very small (smaller than a 1/1024th note), they will still get deleted, but this shouldn't be an issue in practice.
> 
> If you try again with the new version [v2.0 beta 2](https://github.com/adamjmurray/ableton-midi-sculptor/blob/master/releases/2.0-beta-2/Sculptor.amxd?raw=true), it should work a lot better now!

This resolved any headaches I have had with abletons midi limitations. Thank you.
